default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: instacl02_development
test:
  <<: *default
  database: instacl02_test

production:
  <<: *default
  database: instacl02_production
  username: instacl02
  password: <%= ENV['instacl02_DATABASE_PASSWORD'] %>